### ISSUE TITLE
Abandoned requirements

### ISSUE THREAD

**Issue by jerry1970** [ProfessionalWiki/ModernTimeline#17]
### Setup

- MW version: 1.34.1
- PHP version: 7.2.31 (litespeed)
- DB (MySQL etc.): 10.2.27-MariaDB-cll-lve
- SMW version: 3.1.6
- MT version: 1.2.0

### Issue

I added the requirement to composer.local.json:

```json
{
	"require": {
		"mediawiki/semantic-media-wiki": "~3.0",
		"professional-wiki/modern-timeline": "~1.0"
	}
}
```

Then I ran this to install:
```bash
composer update --no-dev
```

And I got these warnings:
```
  - Installing professional-wiki/modern-timeline (1.2.0): Downloading (100%)         
Package guzzlehttp/ringphp is abandoned, you should avoid using it. No replacement was suggested.
Package guzzlehttp/streams is abandoned, you should avoid using it. No replacement was suggested.
```

It works but that might not be the case in the future...

**Comment by JeroenDeDauw** [comment]
This extension does not require Guzzle. MediaWiki does for some time now. This is likely where your warning is coming from.
