### ISSUE TITLE
Image previews in timeline 

### ISSUE THREAD

**Issue by krabina** [ProfessionalWiki/ModernTimeline#9]
### Feature request:
In the original TimlineJS, not only is a image displayed above the timline, but also small preview in the timlineband:
![grafik](https://user-images.githubusercontent.com/4318745/63348750-3aa6e580-c35a-11e9-937d-a9ebfb150a4f.png)

In the extension, this should be done with a configuration option to have more flexibility. E. g. in my ask query I can specify an image link as a printout and use this in the template to format the big picture above the timline.

If I now could add an option like 
|showpreview=yes
that would display these small previews in the timline, we would be quite flexible.

**Comment by JeroenDeDauw** [comment]
`showpreview=yes` would pick the first image in the result I assume.

What about instead having a `image=PropertyName` parameter?

**Comment by krabina** [comment]
yes, even better!

**Comment by JeroenDeDauw** [comment]
I had a look at this to see if I could quickly add image support. Apparently not. Can do for 300 EUR (which is a discounted rate).

**Comment by JeroenDeDauw** [comment]
I added an `image property` parameter in 1.2.0. See the docs in README. Images are shown both as super-small thumbnail and on the "event slide". No way to control the image sizes via the timeline JSON so I'm not sure how useful this actually is.
